### ISSUE TITLE
Compatibality

### ISSUE THREAD

**Issue by zakirIndia** [aleju/self-driving-truck#3]
I have 
8 GB Ram
AMD Graphics
i5 8th Gen
Ubuntu 18.04.1 
Does this work for me
Thankyou

**Comment by aleju** [comment]
The CPU should be fast enough. I think ubuntu 18 is fine, though it was only tested in older versions.
The RAM might not be enough (can't remember how much it needed).
An AMD GPU will also likely not work. Most deep learning libraries can only handle nvidia GPUs.
